export const ENDPOINT_CATALOG: { method: string; path: string; purpose: string }[] = [
  { method: 'GET', path: '/api/status', purpose: 'Gateway status (providers, version, active book).' },
  { method: 'GET', path: '/api/books', purpose: 'List books.' },
  { method: 'POST', path: '/api/books', purpose: 'Create a book.' },
  { method: 'GET', path: '/api/books/:slug', purpose: 'Get one book.' },
  { method: 'POST', path: '/api/projects/create', purpose: 'Create + auto-execute a project.' },
  { method: 'POST', path: '/api/pipeline/create', purpose: 'Create a full novel pipeline.' },
  { method: 'POST', path: '/api/chat', purpose: 'Chat with the agent.' },
  { method: 'GET', path: '/api/personas', purpose: 'List author personas.' },
  { method: 'POST', path: '/api/personas', purpose: 'Create an author persona.' },
  { method: 'GET', path: '/api/series', purpose: 'List series.' },
  { method: 'POST', path: '/api/kdp/export-blurb', purpose: 'Generate a KDP blurb.' },
  { method: 'POST', path: '/api/projects/:id/beta-reader', purpose: 'Run the AI beta-reader panel.' },
  { method: 'POST', path: '/api/audio/generate', purpose: 'Generate TTS audio.' },
  { method: 'POST', path: '/api/images/book-cover', purpose: 'Generate a book cover.' },
  { method: 'GET', path: '/api/confirmations', purpose: 'List pending confirmation-gate items.' },
  { method: 'POST', path: '/api/confirmations/:id/approve', purpose: 'Approve a gated action (requires explicit human intent).' },
  { method: 'GET', path: '/api/backups', purpose: 'List backups.' },
  { method: 'GET', path: '/api/library', purpose: 'Library overview.' },
  { method: 'GET', path: '/api/forms', purpose: 'List story forms + word bands.' },
  { method: 'GET', path: '/api/structures', purpose: 'List story structures.' },
  { method: 'GET', path: '/api/books/:slug/structure-review', purpose: 'Book structure review (beat→outline mapping vs the declared structure).' },
  { method: 'GET', path: '/api/books/:slug/length-review', purpose: 'Book length review (per-chapter actual vs target + band check).' },
  { method: 'POST', path: '/api/books/:slug/consistency-audit', purpose: 'Run the per-book consistency (fact-ledger) audit; report via GET …/consistency-report.' },
  { method: 'GET', path: '/api/worlds', purpose: 'List worlds (worldbuilding repositories).' },
  { method: 'PUT', path: '/api/books/:slug/world', purpose: 'Bind a book to a world (auto-builds its curated bible via relevance-pull).' },
];
// This is a curated subset. BookClaw exposes ~284 routes; see
// ../gateway/src/api/routes/*.routes.ts for the complete list.
