import { join } from 'path';
import fs from 'fs/promises';
import { randomBytes } from 'crypto';
import { Vault } from '../security/vault.js';
import { PermissionManager } from '../security/permissions.js';
import { AuditLog } from '../security/audit.js';
import { SandboxGuard } from '../security/sandbox.js';
import { InjectionDetector } from '../security/injection.js';
import { ActivityLog } from '../services/activity-log.js';
import { ROOT_DIR } from '../paths.js';
import type { BookClawGateway } from '../index.js';

/**
 * Persist a generated auth token to .env, then tighten perms to 0600.
 * The token grants full API access and must not be world/group-readable
 * (mirrors the vault's own .env creation). appendFile can create .env at the
 * default 0644 when BOOKCLAW_VAULT_KEY is supplied via env and no .env exists
 * yet, so the chmod is what closes the exposure. Non-fatal on filesystems that
 * don't support chmod.
 */
export async function persistAuthToken(envPath: string, token: string): Promise<void> {
  await fs.appendFile(
    envPath,
    `\n# Auto-generated by BookClaw — HTTP/WebSocket auth token\nBOOKCLAW_AUTH_TOKEN=${token}\n`,
  );
  try {
    if (process.platform !== 'win32') await fs.chmod(envPath, 0o600);
  } catch { /* chmod unsupported — leave default perms */ }
}

/**
 * Phase 2: security layer (+ Phase 2c API auth token, CORS/IP posture logging,
 * and Phase 2b activity log). CORS/IP posture is computed in the constructor;
 * this only logs it after the auth token is resolved.
 */
export async function initSecurity(gw: BookClawGateway): Promise<void> {
  // ── Phase 2: Security Layer ──
  gw.vault = new Vault(join(ROOT_DIR, 'config', '.vault'));
  await gw.vault.initialize();
  console.log('  ✓ Encrypted vault initialized (AES-256-GCM)');

  gw.permissions = new PermissionManager(gw.config.get('security.permissionPreset', 'standard'));
  console.log(`  ✓ Permissions: ${gw.permissions.preset} mode`);

  gw.audit = new AuditLog(join(ROOT_DIR, 'workspace', '.audit'));
  await gw.audit.initialize();
  console.log('  ✓ Audit logging active');

  gw.sandbox = new SandboxGuard(join(ROOT_DIR, 'workspace'));
  console.log('  ✓ Sandbox: workspace-only file access');

  gw.injectionDetector = new InjectionDetector();
  console.log('  ✓ Prompt injection detection active');

  // ── Phase 2c: API auth token ──
  // Gates /api/* and the Socket.IO handshake. Mirrors the BOOKCLAW_VAULT_KEY
  // pattern: read from env (.env already loaded by dotenv), else generate and
  // persist to .env. BOOKCLAW_AUTH_DISABLED=1 turns the gate off entirely.
  if (process.env.BOOKCLAW_AUTH_DISABLED === '1') {
    gw.authToken = null;
    console.warn('  ⚠️  AUTH DISABLED — BOOKCLAW_AUTH_DISABLED=1 is set.');
    console.warn('     Every host that can reach this server can drive the agent unauthenticated.');
  } else {
    let token = (process.env.BOOKCLAW_AUTH_TOKEN || '').trim();
    if (!token) {
      token = randomBytes(32).toString('hex');
      const envPath = join(ROOT_DIR, '.env');
      try {
        await persistAuthToken(envPath, token);
        console.log('  🔑 Generated API auth token and saved to .env.');
      } catch {
        console.warn('  ⚠️  WARNING: Could not write auth token to .env — using a random session token.');
        console.warn('     Set BOOKCLAW_AUTH_TOKEN in the environment for production use.');
      }
      process.env.BOOKCLAW_AUTH_TOKEN = token;
    }
    gw.authToken = token;
    console.log('  ✓ API authentication active (bearer token on /api/* and WebSocket)');
  }

  // CORS posture (computed in the constructor; applied to Express + Socket.IO).
  if (gw.corsWildcard) {
    console.warn(`  ${gw.corsSummary}`);
  } else {
    console.log(`  ${gw.corsSummary}`);
  }

  // Source-IP allowlist posture (computed in the constructor).
  console.log(`  ${gw.ipAllowlistSummary}`);

  // API rate-limit posture (computed in the constructor).
  console.log(`  ${gw.rateLimitSummary}`);

  // ── Phase 2b: Activity Log ──
  gw.activityLog = new ActivityLog(join(ROOT_DIR, 'workspace'));
  await gw.activityLog.initialize();
  console.log('  ✓ Activity log initialized');
}
